queue_rules:
  - name: default
    merge_method: squash

pull_request_rules:
  - name: auto-merge auto-update PRs
    conditions:
      - head=auto-update
      - author=turtton
      - check-success="build"
    actions:
      queue:
        name: default
